name: Release

on:
  push:
    branches:
      - main
      - init

jobs:
  build:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/docker-build-and-validate.yml@v0.60.0
    with:
      github_advanced_security_enabled: true
      kics_enabled: false # Migrating existing configurations from CI to base-image, security findings should be addressed
      trivy_ignore_failure: true
      aws_region: us-east-2

  create-tag:
    uses: consensys-vertical-apps/shared-services-workflows/.github/workflows/create-eph-tag.yml@v0.60.0

  push-uat:
    runs-on: ubuntu-latest
    environment: uat
    needs: [build, create-tag]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Push
        uses: consensys-vertical-apps/shared-services-workflows/.github/actions/docker-push-ecr-public@ecr-public
        with:
          image_tag: ${{ needs.update-tag.outputs.create-tag }}
          aws_role: arn:aws:iam::722264665990:role/ecr-github-metamask-core-staging-metamask-extension-e2e
          aws_region: us-east-2
          public_ecr_repository: public.ecr.aws/y2l1v8k6/metamask-core-staging/metamask-extension-e2e

#   push-prod:
#     runs-on: ubuntu-latest
#     environment: prd
#     needs: [push-uat, update-tag]
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - name: Push
#         uses: consensys-vertical-apps/shared-services-workflows/.github/actions/docker-push@v0.55.1
#         with:
#           image_tag: ${{ needs.update-tag.outputs.tag }}
#           aws_role: ${{ vars.PRD_AWS_EKS_ROLE_ARN }}
#           aws_region: us-east-2
#           ecr_repository: staking/prd/api-gateway